patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: tylerstewart 
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: tylerstewart
issuehunt: trs
otechie: # Replace with a single Otechie username
custom: ['https://paypal.me/hellotrs', 'buymeacoff.ee/tylerstewart'] # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
